services:
  judge.master:
    image: codeforge.master:latest
    build:
      context: ./judge
      dockerfile: Dockerfiles/master/Dockerfile
    env_file: judge/Dockerfiles/master/master.env
    ports:
      - "7000:7000"
    networks:
      - public_net
      - private_net
    depends_on:
    - database
    volumes:
      - type: bind
        source: ./judge/master/bin
        target: /dev_master
      - type: bind
        source: ./judge/scraped_questions
        target: /questionsDir

  judge.worker.cpp:
    image: codeforge.cpp:latest
    build:
      context: ./judge
      dockerfile: Dockerfiles/cpp/Dockerfile.cpp.prod
    env_file: judge/Dockerfiles/cpp/cpp.env
    ports:
      - "8000:8000"
    networks:
      - private_net
    volumes:
      - type: bind
        source: ./judge/worker/bin
        target: /dev_worker
      - type: bind
        source: ./judge/scraped_questions
        target: /questionsDir
    depends_on:
    - judge.master

  judge.worker.cpp20:
    image: codeforge.cpp20:latest
    build:
      context: ./judge
      dockerfile: Dockerfiles/cpp20/Dockerfile.cpp.prod
    env_file: judge/Dockerfiles/cpp20/cpp.env
    networks:
      - private_net
    volumes:
      - type: bind
        source: ./judge/worker/bin
        target: /dev_worker
      - type: bind
        source: ./judge/scraped_questions
        target: /questionsDir
    depends_on:
    - judge.master

  judge.worker.cpp23:
    image: codeforge.cpp23:latest
    build:
      context: ./judge
      dockerfile: Dockerfiles/cpp23/Dockerfile.cpp.prod
    env_file: judge/Dockerfiles/cpp23/cpp.env
    networks:
      - private_net
    volumes:
      - type: bind
        source: ./judge/worker/bin
        target: /dev_worker
      - type: bind
        source: ./judge/scraped_questions
        target: /questionsDir
    depends_on:
    - judge.master

  judge.worker.c:
    image: codeforge.c:latest
    build:
      context: ./judge
      dockerfile: Dockerfiles/c/Dockerfile.c.prod
    env_file: judge/Dockerfiles/c/c.env
    ports:
      - "8001:8000"
    networks:
      - private_net
    volumes:
      - type: bind
        source: ./judge/worker/bin
        target: /dev_worker
      - type: bind
        source: ./judge/scraped_questions
        target: /questionsDir
    depends_on:
    - judge.master

  judge.worker.python:
    image: codeforge.python:latest
    build:
      context: ./judge
      dockerfile: Dockerfiles/python/Dockerfile.python.prod
    env_file: judge/Dockerfiles/python/python.env
    ports:
      - "8002:8000"
    networks:
      - private_net
    volumes:
      - type: bind
        source: ./judge/worker/bin
        target: /dev_worker
      - type: bind
        source: ./judge/scraped_questions
        target: /questionsDir
    depends_on:
    - judge.master

  judge.worker.node:
    image: codeforge.node:latest
    build:
      context: ./judge
      dockerfile: Dockerfiles/node/Dockerfile.node.prod
    env_file: judge/Dockerfiles/node/node.env
    ports:
      - "8003:8000"
    networks:
      - private_net
    volumes:
      - type: bind
        source: ./judge/worker/bin
        target: /dev_worker
      - type: bind
        source: ./judge/scraped_questions
        target: /questionsDir
    depends_on:
    - judge.master

  database:
    image: postgres:18-trixie
    restart: on-failure
    user: postgres
    volumes:
      - db-cluster:/var/lib/postgresql
    env_file: db/env.dev
    ports:
      - "5432:5432"
    networks:
      - public_net
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-cluster:

networks:
  public_net:
    driver: bridge

  private_net:
    driver: bridge
    internal: true
