# Runners
.PHONY: scraper
scraper:
	go run ./cmd/cses_scraper/scraper.go 

.PHONY: q_scraper
q_scraper:
	go run ./cmd/questions_scraper/main.go 

.PHONY: tc_down
tc_down:
	go run ./cmd/TC_Downloader/scraper.go 

