// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Question struct {
	QuestionID             int32
	QuestionCatagory       pgtype.Text
	QuestionName           pgtype.Text
	QuestionDescription    pgtype.Text
	InputDescription       pgtype.Text
	ConstraintsDescription pgtype.Text
	TimeConstraint         int32
	MemConstraint          int32
	ExampleInputs          []string
	ExampleOutputs         []string
}

type Submission struct {
	SubmissionID   int32
	UserID         int32
	QuestionID     int32
	SubmissionTime pgtype.Timestamp
	SubmitedCode   pgtype.Text
	CodeRuntime    pgtype.Text
	Verdict        pgtype.Text
}

type User struct {
	ID                int32
	Username          pgtype.Text
	Email             pgtype.Text
	EncryptedPassword pgtype.Text
	Role              pgtype.Text
	CreatedAt         pgtype.Timestamp
	LastOnline        pgtype.Timestamp
}

type VerdictStat struct {
	SubmissionID              int32
	MemUsage                  int32
	TimeMs                    int32
	NotAcceptedTestCase       pgtype.Int4
	NotAcceptedTestCaseStdout pgtype.Text
	Stderr                    pgtype.Text
}
