// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestion = `-- name: CreateQuestion :exec
INSERT INTO questions (
    question_id,
    question_catagory,
    question_name,
    question_description,
    input_description,
    constraints_description,
    time_constraint,
    mem_constraint,
    example_inputs,
    example_outputs
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreateQuestionParams struct {
	QuestionID             int32
	QuestionCatagory       pgtype.Text
	QuestionName           pgtype.Text
	QuestionDescription    pgtype.Text
	InputDescription       pgtype.Text
	ConstraintsDescription pgtype.Text
	TimeConstraint         int32
	MemConstraint          int32
	ExampleInputs          []string
	ExampleOutputs         []string
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) error {
	_, err := q.db.Exec(ctx, createQuestion,
		arg.QuestionID,
		arg.QuestionCatagory,
		arg.QuestionName,
		arg.QuestionDescription,
		arg.InputDescription,
		arg.ConstraintsDescription,
		arg.TimeConstraint,
		arg.MemConstraint,
		arg.ExampleInputs,
		arg.ExampleOutputs,
	)
	return err
}

const createSubmissionAndReturnId = `-- name: CreateSubmissionAndReturnId :one
INSERT INTO submissions (
  user_id,
  question_id,
  submission_time,
  submited_code,
  code_runtime,
  verdict
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING submission_id
`

type CreateSubmissionAndReturnIdParams struct {
	UserID         int32
	QuestionID     int32
	SubmissionTime pgtype.Timestamp
	SubmitedCode   pgtype.Text
	CodeRuntime    pgtype.Text
	Verdict        pgtype.Text
}

func (q *Queries) CreateSubmissionAndReturnId(ctx context.Context, arg CreateSubmissionAndReturnIdParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSubmissionAndReturnId,
		arg.UserID,
		arg.QuestionID,
		arg.SubmissionTime,
		arg.SubmitedCode,
		arg.CodeRuntime,
		arg.Verdict,
	)
	var submission_id int32
	err := row.Scan(&submission_id)
	return submission_id, err
}

const createUserAndReturnId = `-- name: CreateUserAndReturnId :one
INSERT INTO users (
  username,
  email,
  encrypted_password,
  role,
  created_at,
  last_online
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id
`

type CreateUserAndReturnIdParams struct {
	Username          pgtype.Text
	Email             pgtype.Text
	EncryptedPassword pgtype.Text
	Role              pgtype.Text
	CreatedAt         pgtype.Timestamp
	LastOnline        pgtype.Timestamp
}

func (q *Queries) CreateUserAndReturnId(ctx context.Context, arg CreateUserAndReturnIdParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUserAndReturnId,
		arg.Username,
		arg.Email,
		arg.EncryptedPassword,
		arg.Role,
		arg.CreatedAt,
		arg.LastOnline,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createVerdictStatsRecord = `-- name: CreateVerdictStatsRecord :exec
INSERT INTO verdict_stats (
  submission_id,
  mem_usage,
  time_ms,
  not_accepted_test_case,
  not_accepted_test_case_stdout,
  stderr
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateVerdictStatsRecordParams struct {
	SubmissionID              int32
	MemUsage                  int32
	TimeMs                    int32
	NotAcceptedTestCase       pgtype.Int4
	NotAcceptedTestCaseStdout pgtype.Text
	Stderr                    pgtype.Text
}

func (q *Queries) CreateVerdictStatsRecord(ctx context.Context, arg CreateVerdictStatsRecordParams) error {
	_, err := q.db.Exec(ctx, createVerdictStatsRecord,
		arg.SubmissionID,
		arg.MemUsage,
		arg.TimeMs,
		arg.NotAcceptedTestCase,
		arg.NotAcceptedTestCaseStdout,
		arg.Stderr,
	)
	return err
}

const getTimeAndMemConstraints = `-- name: GetTimeAndMemConstraints :one
SELECT 
  time_constraint,mem_constraint
FROM questions
WHERE question_id = $1
LIMIT 1
`

type GetTimeAndMemConstraintsRow struct {
	TimeConstraint int32
	MemConstraint  int32
}

func (q *Queries) GetTimeAndMemConstraints(ctx context.Context, questionID int32) (GetTimeAndMemConstraintsRow, error) {
	row := q.db.QueryRow(ctx, getTimeAndMemConstraints, questionID)
	var i GetTimeAndMemConstraintsRow
	err := row.Scan(&i.TimeConstraint, &i.MemConstraint)
	return i, err
}

const getVerdictStats = `-- name: GetVerdictStats :one
SELECT submission_id, mem_usage, time_ms, not_accepted_test_case, not_accepted_test_case_stdout, stderr FROM verdict_stats
WHERE submission_id = $1
LIMIT 1
`

func (q *Queries) GetVerdictStats(ctx context.Context, submissionID int32) (VerdictStat, error) {
	row := q.db.QueryRow(ctx, getVerdictStats, submissionID)
	var i VerdictStat
	err := row.Scan(
		&i.SubmissionID,
		&i.MemUsage,
		&i.TimeMs,
		&i.NotAcceptedTestCase,
		&i.NotAcceptedTestCaseStdout,
		&i.Stderr,
	)
	return i, err
}

const questionExists = `-- name: QuestionExists :one
SELECT EXISTS (
    SELECT 1
    FROM questions
    WHERE question_id = $1
)
`

func (q *Queries) QuestionExists(ctx context.Context, questionID int32) (bool, error) {
	row := q.db.QueryRow(ctx, questionExists, questionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateVerdictForSubmition = `-- name: UpdateVerdictForSubmition :exec
UPDATE submissions 
SET verdict = $2
WHERE submission_id = $1
`

type UpdateVerdictForSubmitionParams struct {
	SubmissionID int32
	Verdict      pgtype.Text
}

func (q *Queries) UpdateVerdictForSubmition(ctx context.Context, arg UpdateVerdictForSubmitionParams) error {
	_, err := q.db.Exec(ctx, updateVerdictForSubmition, arg.SubmissionID, arg.Verdict)
	return err
}
