// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestion = `-- name: CreateQuestion :exec
INSERT INTO questions (
    question_id,
    question_category,
    question_name,
    question_description,
    input_description,
    output_description,
    constraints_description,
    time_constraint,
    mem_constraint,
    example_inputs,
    example_outputs
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreateQuestionParams struct {
	QuestionID             int32
	QuestionCategory       pgtype.Text
	QuestionName           pgtype.Text
	QuestionDescription    pgtype.Text
	InputDescription       pgtype.Text
	OutputDescription      pgtype.Text
	ConstraintsDescription pgtype.Text
	TimeConstraint         int32
	MemConstraint          int32
	ExampleInputs          []string
	ExampleOutputs         []string
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) error {
	_, err := q.db.Exec(ctx, createQuestion,
		arg.QuestionID,
		arg.QuestionCategory,
		arg.QuestionName,
		arg.QuestionDescription,
		arg.InputDescription,
		arg.OutputDescription,
		arg.ConstraintsDescription,
		arg.TimeConstraint,
		arg.MemConstraint,
		arg.ExampleInputs,
		arg.ExampleOutputs,
	)
	return err
}

const createSubmissionAndReturnId = `-- name: CreateSubmissionAndReturnId :one
INSERT INTO submissions (
  user_id,
  question_id,
  submission_time,
  submited_code,
  code_runtime,
  verdict
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING submission_id
`

type CreateSubmissionAndReturnIdParams struct {
	UserID         int32
	QuestionID     int32
	SubmissionTime pgtype.Timestamp
	SubmitedCode   pgtype.Text
	CodeRuntime    pgtype.Text
	Verdict        pgtype.Text
}

func (q *Queries) CreateSubmissionAndReturnId(ctx context.Context, arg CreateSubmissionAndReturnIdParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSubmissionAndReturnId,
		arg.UserID,
		arg.QuestionID,
		arg.SubmissionTime,
		arg.SubmitedCode,
		arg.CodeRuntime,
		arg.Verdict,
	)
	var submission_id int32
	err := row.Scan(&submission_id)
	return submission_id, err
}

const createUserAndReturnId = `-- name: CreateUserAndReturnId :one
INSERT INTO users (
  username,
  email,
  encrypted_password,
  role,
  created_at,
  last_online
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id
`

type CreateUserAndReturnIdParams struct {
	Username          pgtype.Text
	Email             pgtype.Text
	EncryptedPassword pgtype.Text
	Role              pgtype.Text
	CreatedAt         pgtype.Timestamp
	LastOnline        pgtype.Timestamp
}

func (q *Queries) CreateUserAndReturnId(ctx context.Context, arg CreateUserAndReturnIdParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUserAndReturnId,
		arg.Username,
		arg.Email,
		arg.EncryptedPassword,
		arg.Role,
		arg.CreatedAt,
		arg.LastOnline,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createVerdictStatsRecord = `-- name: CreateVerdictStatsRecord :exec
INSERT INTO verdict_stats (
  submission_id,
  mem_usage,
  time_ms,
  not_accepted_test_case,
  not_accepted_test_case_stdout,
  stderr
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateVerdictStatsRecordParams struct {
	SubmissionID              int32
	MemUsage                  int32
	TimeMs                    int32
	NotAcceptedTestCase       pgtype.Int4
	NotAcceptedTestCaseStdout pgtype.Text
	Stderr                    pgtype.Text
}

func (q *Queries) CreateVerdictStatsRecord(ctx context.Context, arg CreateVerdictStatsRecordParams) error {
	_, err := q.db.Exec(ctx, createVerdictStatsRecord,
		arg.SubmissionID,
		arg.MemUsage,
		arg.TimeMs,
		arg.NotAcceptedTestCase,
		arg.NotAcceptedTestCaseStdout,
		arg.Stderr,
	)
	return err
}

const getAllQuestionsMinimalDetails = `-- name: GetAllQuestionsMinimalDetails :many
SELECT 
  question_id,
  question_name,
  question_category
FROM questions
`

type GetAllQuestionsMinimalDetailsRow struct {
	QuestionID       int32
	QuestionName     pgtype.Text
	QuestionCategory pgtype.Text
}

func (q *Queries) GetAllQuestionsMinimalDetails(ctx context.Context) ([]GetAllQuestionsMinimalDetailsRow, error) {
	rows, err := q.db.Query(ctx, getAllQuestionsMinimalDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllQuestionsMinimalDetailsRow
	for rows.Next() {
		var i GetAllQuestionsMinimalDetailsRow
		if err := rows.Scan(&i.QuestionID, &i.QuestionName, &i.QuestionCategory); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSubmissionOfQuestion = `-- name: GetAllSubmissionOfQuestion :many
SELECT 
s.submission_id,
s.question_id,
s.verdict,
v.mem_usage,
v.time_ms, v.not_accepted_test_case, v.not_accepted_test_case_stdout, v.stderr, s.submission_time
FROM submissions s 
LEFT JOIN verdict_stats v ON s.submission_id = v.submission_id
WHERE s.question_id = $1 AND s.user_id = $2
`

type GetAllSubmissionOfQuestionParams struct {
	QuestionID int32
	UserID     int32
}

type GetAllSubmissionOfQuestionRow struct {
	SubmissionID              int32
	QuestionID                int32
	Verdict                   pgtype.Text
	MemUsage                  pgtype.Int4
	TimeMs                    pgtype.Int4
	NotAcceptedTestCase       pgtype.Int4
	NotAcceptedTestCaseStdout pgtype.Text
	Stderr                    pgtype.Text
	SubmissionTime            pgtype.Timestamp
}

func (q *Queries) GetAllSubmissionOfQuestion(ctx context.Context, arg GetAllSubmissionOfQuestionParams) ([]GetAllSubmissionOfQuestionRow, error) {
	rows, err := q.db.Query(ctx, getAllSubmissionOfQuestion, arg.QuestionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSubmissionOfQuestionRow
	for rows.Next() {
		var i GetAllSubmissionOfQuestionRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.QuestionID,
			&i.Verdict,
			&i.MemUsage,
			&i.TimeMs,
			&i.NotAcceptedTestCase,
			&i.NotAcceptedTestCaseStdout,
			&i.Stderr,
			&i.SubmissionTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestion = `-- name: GetQuestion :one
SELECT question_id, question_category, question_name, question_description, input_description, output_description, constraints_description, time_constraint, mem_constraint, example_inputs, example_outputs
FROM questions 
WHERE question_id = $1
`

func (q *Queries) GetQuestion(ctx context.Context, questionID int32) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestion, questionID)
	var i Question
	err := row.Scan(
		&i.QuestionID,
		&i.QuestionCategory,
		&i.QuestionName,
		&i.QuestionDescription,
		&i.InputDescription,
		&i.OutputDescription,
		&i.ConstraintsDescription,
		&i.TimeConstraint,
		&i.MemConstraint,
		&i.ExampleInputs,
		&i.ExampleOutputs,
	)
	return i, err
}

const getSubmissionVerdict = `-- name: GetSubmissionVerdict :one
SELECT 
s.submission_id,
s.question_id,
s.verdict,
v.mem_usage,
v.time_ms, v.not_accepted_test_case, v.not_accepted_test_case_stdout, v.stderr, s.submission_time
FROM submissions s 
LEFT JOIN verdict_stats v ON s.submission_id = v.submission_id
WHERE s.submission_id = $1
`

type GetSubmissionVerdictRow struct {
	SubmissionID              int32
	QuestionID                int32
	Verdict                   pgtype.Text
	MemUsage                  pgtype.Int4
	TimeMs                    pgtype.Int4
	NotAcceptedTestCase       pgtype.Int4
	NotAcceptedTestCaseStdout pgtype.Text
	Stderr                    pgtype.Text
	SubmissionTime            pgtype.Timestamp
}

func (q *Queries) GetSubmissionVerdict(ctx context.Context, submissionID int32) (GetSubmissionVerdictRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionVerdict, submissionID)
	var i GetSubmissionVerdictRow
	err := row.Scan(
		&i.SubmissionID,
		&i.QuestionID,
		&i.Verdict,
		&i.MemUsage,
		&i.TimeMs,
		&i.NotAcceptedTestCase,
		&i.NotAcceptedTestCaseStdout,
		&i.Stderr,
		&i.SubmissionTime,
	)
	return i, err
}

const getSubmissionVerdictAndQuestionid = `-- name: GetSubmissionVerdictAndQuestionid :one
SELECT verdict,question_id FROM submissions
WHERE submission_id = $1
LIMIT 1
`

type GetSubmissionVerdictAndQuestionidRow struct {
	Verdict    pgtype.Text
	QuestionID int32
}

func (q *Queries) GetSubmissionVerdictAndQuestionid(ctx context.Context, submissionID int32) (GetSubmissionVerdictAndQuestionidRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionVerdictAndQuestionid, submissionID)
	var i GetSubmissionVerdictAndQuestionidRow
	err := row.Scan(&i.Verdict, &i.QuestionID)
	return i, err
}

const getTimeAndMemConstraints = `-- name: GetTimeAndMemConstraints :one
SELECT 
  time_constraint,mem_constraint
FROM questions
WHERE question_id = $1
LIMIT 1
`

type GetTimeAndMemConstraintsRow struct {
	TimeConstraint int32
	MemConstraint  int32
}

func (q *Queries) GetTimeAndMemConstraints(ctx context.Context, questionID int32) (GetTimeAndMemConstraintsRow, error) {
	row := q.db.QueryRow(ctx, getTimeAndMemConstraints, questionID)
	var i GetTimeAndMemConstraintsRow
	err := row.Scan(&i.TimeConstraint, &i.MemConstraint)
	return i, err
}

const getVerdictStats = `-- name: GetVerdictStats :one
SELECT submission_id, mem_usage, time_ms, not_accepted_test_case, not_accepted_test_case_stdout, stderr FROM verdict_stats
WHERE submission_id = $1
LIMIT 1
`

func (q *Queries) GetVerdictStats(ctx context.Context, submissionID int32) (VerdictStat, error) {
	row := q.db.QueryRow(ctx, getVerdictStats, submissionID)
	var i VerdictStat
	err := row.Scan(
		&i.SubmissionID,
		&i.MemUsage,
		&i.TimeMs,
		&i.NotAcceptedTestCase,
		&i.NotAcceptedTestCaseStdout,
		&i.Stderr,
	)
	return i, err
}

const questionExists = `-- name: QuestionExists :one
SELECT EXISTS (
    SELECT 1
    FROM questions
    WHERE question_id = $1
)
`

func (q *Queries) QuestionExists(ctx context.Context, questionID int32) (bool, error) {
	row := q.db.QueryRow(ctx, questionExists, questionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateVerdictForSubmition = `-- name: UpdateVerdictForSubmition :exec
UPDATE submissions 
SET verdict = $2
WHERE submission_id = $1
`

type UpdateVerdictForSubmitionParams struct {
	SubmissionID int32
	Verdict      pgtype.Text
}

func (q *Queries) UpdateVerdictForSubmition(ctx context.Context, arg UpdateVerdictForSubmitionParams) error {
	_, err := q.db.Exec(ctx, updateVerdictForSubmition, arg.SubmissionID, arg.Verdict)
	return err
}
